[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/pedidos"
  to = "/pedidos.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 